{% set version = "0.2.14" %}

package:
  name: ros-industrial-cmake-boilerplate
  version: {{ version }}

source:
  - git_url: https://github.com/ros-industrial/ros_industrial_cmake_boilerplate.git
    git_rev: {{ version }}
    folder: src

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gtest
    - gmock
    - cmake
    - ninja # [win]
    - make # [linux]
    - lcov # [linux]

test:
  commands:
    - test -d ${PREFIX}/lib/cmake/ros_industrial_cmake_boilerplate  # [unix]
    - test -f ${PREFIX}/lib/cmake/ros_industrial_cmake_boilerplate/ros_industrial_cmake_boilerplate-config.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\ros_industrial_cmake_boilerplate (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\ros_industrial_cmake_boilerplate\ros_industrial_cmake_boilerplate-config.cmake (exit 1)  # [win]

build:
  number: 4

about:
  home: https://github.com/ros-industrial/ros_industrial_cmake_boilerplate
  summary: A collection of boilerplate CMake scripts and marcos
  license: Apache-2.0 AND BSD-3-Clause
  license_file: 
    - src/LICENSE
    - src/LICENSE.Apache-2.0
    - src/LICENSE.BSD-3-Clause

extra:
  recipe-maintainers:
    - johnwason
  