{% set version = "0.5.3" %}

package:
  name: ros-industrial-cmake-boilerplate
  version: {{ version }}

source:
  - url: https://github.com/ros-industrial/ros_industrial_cmake_boilerplate/archive/refs/tags/{{ version }}.tar.gz
    sha256: ab8ec7d9ee166c5af43ee7ff159210efca787628f8e98e0fdd9fbab3292b5c63
    folder: src/ros_industrial_cmake_boilerplate

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gtest
    - gmock
    - cmake
    - ninja # [win]
    - make # [linux]
    - lcov # [linux]

test:
  commands:
    - test -d ${PREFIX}/lib/cmake/ros_industrial_cmake_boilerplate  # [unix]
    - test -f ${PREFIX}/lib/cmake/ros_industrial_cmake_boilerplate/ros_industrial_cmake_boilerplate-config.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\ros_industrial_cmake_boilerplate (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\ros_industrial_cmake_boilerplate\ros_industrial_cmake_boilerplate-config.cmake (exit 1)  # [win]

build:
  number: 0

about:
  home: https://github.com/ros-industrial/ros_industrial_cmake_boilerplate
  summary: A collection of boilerplate CMake scripts and marcos
  license: Apache-2.0 AND BSD-3-Clause
  license_file: 
    - src/ros_industrial_cmake_boilerplate/LICENSE
    - src/ros_industrial_cmake_boilerplate/LICENSE.Apache-2.0
    - src/ros_industrial_cmake_boilerplate/LICENSE.BSD-3-Clause

extra:
  recipe-maintainers:
    - johnwason
  